#!/usr/bin/env bash
# Bootstrap the Don’t Waste CLI from a local checkout.
# Does not configure agents and does not run `dont-waste init`.
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"
CLI_ENTRY="$REPO_ROOT/apps/cli/dist/main.js"
MARKER="dont-waste-local-bootstrap"

DRY_RUN=0
UNINSTALL=0
PREFIX="${DONT_WASTE_PREFIX:-}"

usage() {
  cat <<'EOF'
Don’t Waste local bootstrap (checkout only)

Usage:
  bash scripts/install.sh [options]

Options:
  --help          Show this help
  --dry-run       Print planned actions; do not change HOME/PATH/configs
  --prefix DIR    Install shim under DIR/bin (default: $DONT_WASTE_PREFIX or ~/.local)
  --uninstall     Remove the shim previously written by this script

What this does:
  1. Preflight Node.js >= 22 and Corepack/pnpm
  2. pnpm install && pnpm build in this checkout
  3. Write a reversible `dont-waste` shim that runs apps/cli/dist/main.js

What this does NOT do:
  - Does not run the CLI init command or touch agent configs
  - Does not curl|bash a remote URL
  - Does not publish to npm or install a global npm package named dont-waste

After bootstrap, run `dont-waste` (ensure PREFIX/bin is on PATH). The TUI still
asks for confirmation before configuring adapters.

Remote one-liner install will be enabled only when a public Git URL / npm
package is published.
EOF
}

log() {
  printf '%s\n' "$*"
}

die() {
  printf '%s\n' "$*" >&2
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --help|-h)
      usage
      exit 0
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --uninstall)
      UNINSTALL=1
      shift
      ;;
    --prefix)
      [ "$#" -ge 2 ] || die "--prefix requires a directory"
      PREFIX="$2"
      shift 2
      ;;
    --prefix=*)
      PREFIX="${1#*=}"
      shift
      ;;
    *)
      die "Unknown option: $1 (try --help)"
      ;;
  esac
done

if [ -z "$PREFIX" ]; then
  PREFIX="${HOME:-}/.local"
fi

BIN_DIR="$PREFIX/bin"
SHIM_PATH="$BIN_DIR/dont-waste"
MANIFEST_DIR="$PREFIX/share/dont-waste"
MANIFEST_PATH="$MANIFEST_DIR/local-bootstrap.json"

run_or_plan() {
  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] would run: $*"
  else
    log "+ $*"
    "$@"
  fi
}

write_or_plan() {
  local path="$1"
  local content="$2"
  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] would write: $path"
    log "[dry-run] content preview:"
    printf '%s\n' "$content" | sed 's/^/[dry-run]   /'
  else
    mkdir -p "$(dirname -- "$path")"
    printf '%s\n' "$content" >"$path"
    chmod +x "$path"
    log "Wrote $path"
  fi
}

remove_or_plan() {
  local path="$1"
  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] would remove: $path"
  elif [ -e "$path" ] || [ -L "$path" ]; then
    rm -f "$path"
    log "Removed $path"
  else
    log "Already absent: $path"
  fi
}

preflight_node() {
  if ! command -v node >/dev/null 2>&1; then
    die "Don’t Waste requires Node.js 22 or newer."
  fi
  local major
  major="$(node -p 'process.versions.node.split(".")[0]')"
  if [ "$major" -lt 22 ]; then
    die "Don’t Waste requires Node.js 22 or newer (found $(node --version))."
  fi
  log "Node.js OK: $(node --version)"
}

ensure_pnpm() {
  if command -v pnpm >/dev/null 2>&1; then
    log "pnpm OK: $(command -v pnpm)"
    return 0
  fi
  if command -v corepack >/dev/null 2>&1; then
    run_or_plan corepack enable
    run_or_plan corepack prepare pnpm@10.16.1 --activate
  else
    die "pnpm not found and corepack is unavailable. Install Node.js 22+ with Corepack."
  fi
  if [ "$DRY_RUN" -eq 0 ] && ! command -v pnpm >/dev/null 2>&1; then
    die "pnpm still not on PATH after Corepack prepare."
  fi
}

shim_content() {
  cat <<EOF
#!/usr/bin/env bash
# ${MARKER}
# Generated by Don’t Waste scripts/install.sh — safe to delete via --uninstall.
set -euo pipefail
exec node "$CLI_ENTRY" "\$@"
EOF
}

manifest_content() {
  cat <<EOF
{
  "marker": "${MARKER}",
  "repoRoot": $(node -p "JSON.stringify(process.argv[1])" "$REPO_ROOT"),
  "cliEntry": $(node -p "JSON.stringify(process.argv[1])" "$CLI_ENTRY"),
  "shimPath": $(node -p "JSON.stringify(process.argv[1])" "$SHIM_PATH"),
  "installedAt": $(node -p "JSON.stringify(new Date().toISOString())")
}
EOF
}

do_uninstall() {
  log "Uninstalling local Don’t Waste shim (prefix=$PREFIX)"
  remove_or_plan "$SHIM_PATH"
  remove_or_plan "$MANIFEST_PATH"
  log "Checkout at $REPO_ROOT was not deleted."
  log "Agent configs were not modified."
}

do_install() {
  log "Don’t Waste local bootstrap"
  log "  repo:   $REPO_ROOT"
  log "  prefix: $PREFIX"
  log "  shim:   $SHIM_PATH"
  log "This bootstrap does not configure agents; the CLI still asks before setup."

  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] would check Node.js >= 22"
    log "[dry-run] would ensure corepack/pnpm"
  else
    preflight_node
    ensure_pnpm
  fi

  if [ "${DONT_WASTE_INSTALL_SKIP_FETCH:-}" = "1" ]; then
    if [ "$DRY_RUN" -eq 1 ]; then
      log "[dry-run] DONT_WASTE_INSTALL_SKIP_FETCH=1 — would skip pnpm install/build if dist exists"
    else
      [ -f "$CLI_ENTRY" ] || die "DONT_WASTE_INSTALL_SKIP_FETCH=1 but missing $CLI_ENTRY (run pnpm build first)"
      log "Skipping pnpm install/build (DONT_WASTE_INSTALL_SKIP_FETCH=1); using existing $CLI_ENTRY"
    fi
  else
    if [ "$DRY_RUN" -eq 1 ]; then
      log "[dry-run] would run: pnpm install (in $REPO_ROOT)"
      log "[dry-run] would run: pnpm build (in $REPO_ROOT)"
    else
      (
        cd "$REPO_ROOT"
        pnpm install
        pnpm build
      )
    fi
  fi

  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] would write shim $SHIM_PATH -> node $CLI_ENTRY"
    log "[dry-run] would write manifest $MANIFEST_PATH"
    write_or_plan "$SHIM_PATH" "$(shim_content)"
  else
    [ -f "$CLI_ENTRY" ] || die "Build did not produce $CLI_ENTRY"
    write_or_plan "$SHIM_PATH" "$(shim_content)"
    mkdir -p "$MANIFEST_DIR"
    printf '%s\n' "$(manifest_content)" >"$MANIFEST_PATH"
    log "Wrote $MANIFEST_PATH"
  fi

  log ""
  log "Next steps:"
  log "  1. Ensure $BIN_DIR is on your PATH"
  log "  2. Run: dont-waste --help"
  log "  3. Run: dont-waste   # TUI asks before configuring adapters"
  if [ "$DRY_RUN" -eq 1 ]; then
    log "[dry-run] no files were written; HOME/PATH/configs unchanged"
  fi
}

if [ "$UNINSTALL" -eq 1 ]; then
  do_uninstall
else
  do_install
fi
