# Bootstrap the Don’t Waste CLI from a local checkout.
# Does not configure agents until the interactive CLI is launched.
[CmdletBinding()]
param(
  [switch]$Help,
  [switch]$DryRun,
  [string]$Prefix = "",
  [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
$CliEntry = Join-Path $RepoRoot "apps/cli/dist/main.js"
$Marker = "dont-waste-local-bootstrap"

function Show-Help {
  @"
Don’t Waste local bootstrap (checkout only)

Usage:
  pwsh scripts/install.ps1 [-Help] [-DryRun] [-Prefix <dir>] [-Uninstall]

Options:
  -Help           Show this help
  -DryRun         Print planned actions; do not change HOME/PATH/configs
  -Prefix <dir>   Install shim under <dir>\bin (default: `$env:DONT_WASTE_PREFIX or %LOCALAPPDATA%\dont-waste)
  -Uninstall      Remove the shim previously written by this script

What this does:
  1. Preflight Node.js >= 22 and Corepack/pnpm
  2. pnpm install && pnpm build in this checkout
  3. Write a reversible dont-waste.cmd shim that runs apps/cli/dist/main.js

What this does NOT do:
  - Does not run the CLI init command or touch agent configs
  - Does not publish to npm or install a global npm package named dont-waste

After bootstrap, run dont-waste (ensure Prefix\bin is on PATH). The TUI still
asks for confirmation before configuring adapters.

"@
}

function Write-Log([string]$Message) {
  Write-Host $Message
}

function Require-Node22 {
  if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    throw "Don’t Waste requires Node.js 22 or newer."
  }
  $major = [int]((node -p "process.versions.node.split('.')[0]"))
  if ($major -lt 22) {
    throw "Don’t Waste requires Node.js 22 or newer (found $(node --version))."
  }
  Write-Log "Node.js OK: $(node --version)"
}

function Ensure-Pnpm {
  if (Get-Command pnpm -ErrorAction SilentlyContinue) {
    Write-Log "pnpm OK: $((Get-Command pnpm).Source)"
    return
  }
  if (-not (Get-Command corepack -ErrorAction SilentlyContinue)) {
    throw "pnpm not found and corepack is unavailable. Install Node.js 22+ with Corepack."
  }
  if ($DryRun) {
    Write-Log "[dry-run] would run: corepack enable"
    Write-Log "[dry-run] would run: corepack prepare pnpm@10.16.1 --activate"
    return
  }
  corepack enable
  corepack prepare pnpm@10.16.1 --activate
  if (-not (Get-Command pnpm -ErrorAction SilentlyContinue)) {
    throw "pnpm still not on PATH after Corepack prepare."
  }
}

if ($Help) {
  Show-Help
  exit 0
}

if ([string]::IsNullOrWhiteSpace($Prefix)) {
  if (-not [string]::IsNullOrWhiteSpace($env:DONT_WASTE_PREFIX)) {
    $Prefix = $env:DONT_WASTE_PREFIX
  }
  else {
    $localApp = $env:LOCALAPPDATA
    if ([string]::IsNullOrWhiteSpace($localApp)) {
      $localApp = Join-Path $HOME "AppData\Local"
    }
    $Prefix = Join-Path $localApp "dont-waste"
  }
}

$BinDir = Join-Path $Prefix "bin"
$ShimPath = Join-Path $BinDir "dont-waste.cmd"
$ManifestDir = Join-Path $Prefix "share\dont-waste"
$ManifestPath = Join-Path $ManifestDir "local-bootstrap.json"

$ShimBody = @"
@echo off
REM $Marker
REM Generated by Don’t Waste scripts/install.ps1 — safe to delete via -Uninstall.
node "$CliEntry" %*
"@

function Remove-OrPlan([string]$Path) {
  if ($DryRun) {
    Write-Log "[dry-run] would remove: $Path"
    return
  }
  if (Test-Path -LiteralPath $Path) {
    Remove-Item -LiteralPath $Path -Force
    Write-Log "Removed $Path"
  }
  else {
    Write-Log "Already absent: $Path"
  }
}

if ($Uninstall) {
  Write-Log "Uninstalling local Don’t Waste shim (prefix=$Prefix)"
  Remove-OrPlan $ShimPath
  Remove-OrPlan $ManifestPath
  Write-Log "Checkout at $RepoRoot was not deleted."
  Write-Log "Agent configs were not modified."
  exit 0
}

Write-Log "Don’t Waste local bootstrap"
Write-Log "  repo:   $RepoRoot"
Write-Log "  prefix: $Prefix"
Write-Log "  shim:   $ShimPath"
Write-Log "This bootstrap does not configure agents; the CLI still asks before setup."

if ($DryRun) {
  Write-Log "[dry-run] would check Node.js >= 22"
  Write-Log "[dry-run] would ensure corepack/pnpm"
}
else {
  Require-Node22
  Ensure-Pnpm
}

if ($env:DONT_WASTE_INSTALL_SKIP_FETCH -eq "1") {
  if ($DryRun) {
    Write-Log "[dry-run] DONT_WASTE_INSTALL_SKIP_FETCH=1 — would skip pnpm install/build if dist exists"
  }
  else {
    if (-not (Test-Path -LiteralPath $CliEntry)) {
      throw "DONT_WASTE_INSTALL_SKIP_FETCH=1 but missing $CliEntry (run pnpm build first)"
    }
    Write-Log "Skipping pnpm install/build (DONT_WASTE_INSTALL_SKIP_FETCH=1); using existing $CliEntry"
  }
}
else {
  if ($DryRun) {
    Write-Log "[dry-run] would run: pnpm install (in $RepoRoot)"
    Write-Log "[dry-run] would run: pnpm build (in $RepoRoot)"
  }
  else {
    Push-Location $RepoRoot
    try {
      pnpm install
      pnpm build
    }
    finally {
      Pop-Location
    }
  }
}

if ($DryRun) {
  Write-Log "[dry-run] would write shim $ShimPath -> node $CliEntry"
  Write-Log "[dry-run] would write manifest $ManifestPath"
  Write-Log "[dry-run] content preview:"
  foreach ($line in ($ShimBody -split "`n")) {
    Write-Log "[dry-run]   $line"
  }
  Write-Log "[dry-run] no files were written; HOME/PATH/configs unchanged"
}
else {
  if (-not (Test-Path -LiteralPath $CliEntry)) {
    throw "Build did not produce $CliEntry"
  }
  New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
  Set-Content -LiteralPath $ShimPath -Value $ShimBody -Encoding ASCII
  Write-Log "Wrote $ShimPath"
  New-Item -ItemType Directory -Force -Path $ManifestDir | Out-Null
  $manifest = @{
    marker     = $Marker
    repoRoot   = $RepoRoot
    cliEntry   = $CliEntry
    shimPath   = $ShimPath
    installedAt = (Get-Date).ToUniversalTime().ToString("o")
  } | ConvertTo-Json
  Set-Content -LiteralPath $ManifestPath -Value $manifest -Encoding UTF8
  Write-Log "Wrote $ManifestPath"
}

Write-Log ""
Write-Log "Next steps:"
Write-Log "  1. Ensure $BinDir is on your PATH"
Write-Log "  2. Run: dont-waste --help"
Write-Log "  3. Run: dont-waste   # TUI asks before configuring adapters"
